//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PK_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CROP()
        {
            this.PLOTs = new HashSet<PLOT>();
        }
    
        public int CropID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public int DaysTillHarvest { get; set; }
        public string Season { get; set; }
        public int ShelfLife { get; set; }
        public decimal MarketValue { get; set; }
        public string WaterAmount { get; set; }
        public string CropRotationRecom { get; set; }
        public string HarvestTechniques { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLOT> PLOTs { get; set; }
    }
}
