//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PK_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQUIPMENT()
        {
            this.SCHEDULEs = new HashSet<SCHEDULE>();
        }
    
        public int EquipmentID { get; set; }
        public int FarmID { get; set; }
        public int StatusID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual FARM FARM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULE> SCHEDULEs { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
