//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PK_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public int InventoryID { get; set; }
        public int FarmID { get; set; }
        public int SuppliesID { get; set; }
        public int Quantity { get; set; }
    }
}
