//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PK_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PKEntities : DbContext
    {
        public PKEntities()
            : base("name=PKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CROP> CROPs { get; set; }
        public virtual DbSet<CROP_WATER_STATUS> CROP_WATER_STATUS { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMERROSTER> CUSTOMERROSTERs { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<EQUIPMENT> EQUIPMENTs { get; set; }
        public virtual DbSet<FARM> FARMs { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<PLOT> PLOTs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULEs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<SUPPLy> SUPPLIES { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_POSITION> USER_POSITION { get; set; }
        public virtual DbSet<USERROLE> USERROLEs { get; set; }
    }
}
