//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PK_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLOT
    {
        public int PlotID { get; set; }
        public int FarmID { get; set; }
        public int CropID { get; set; }
        public int CropWaterStatusID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Size { get; set; }
        public string History { get; set; }
        public System.DateTime DatePlantec { get; set; }
    
        public virtual CROP CROP { get; set; }
        public virtual CROP_WATER_STATUS CROP_WATER_STATUS { get; set; }
        public virtual FARM FARM { get; set; }
    }
}
